project_id = "prodigy-board-API"

[api]
enabled = true
port = 54421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54422
shadow_port = 54420
major_version = 17

[studio]
enabled = true
port = 54423
api_url = "http://127.0.0.1"

[storage]
enabled = true
file_size_limit = "10MiB"

[storage.buckets.attachments]
public = false
file_size_limit = "10MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:54421"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = false

[realtime]
enabled = false

[inbucket]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false
